// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"go-chassis_demo/wire_demo/services"
)

// Injectors from wire.go:

func InitTest() (*App, error) {
	userServiceApi := services.NewUserService()
	testServiceApi := services.NewTestService(userServiceApi)
	app := &App{
		TestService: testServiceApi,
	}
	return app, nil
}

// wire.go:

type App struct {
	TestService services.TestServiceApi
}
